name: KyloHome
version: 1.2
author: Jerry Liu/littlefish12345
api-version: 1.12.2
main: xyz.kylo.KyloHome.Home
commands:
  home:
    description: Set players' home.
    usage: /home go|set|del|list